language: php
php:
    - 5.6

before_script:
    - echo '' > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - cp behat.yml.dist behat.yml
    - composer install --dev --prefer-source > /dev/null
    - app/console do:da:cr -e=test > /dev/null
    - app/console do:sc:cr -e=test --no-interaction > /dev/null

    # If you use DB fixtures in your feature suite:
    # - app/console do:fi:lo --no-interaction -e=test > /dev/null

    # If you use real http requests (selenium, goutte) in your feature suite:
    # - sudo apt-get update
    # - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5
    # - sudo sed -i -e "s,/var/www,$(pwd)/web,g" /etc/apache2/sites-available/default
    # - sudo /etc/init.d/apache2 restart
    # - export MINK_EXTENSION_PARAMS='base_url=http://localhost/app_test.php'

    # If you use selenium in your feature suite:
    # - export DISPLAY=:99
    # - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.28.0.jar
    # - java -jar selenium-server-standalone-2.28.0.jar > /dev/null &
    # - sh -e /etc/init.d/xvfb start
    # - sleep 5

notifications:
    email:
        - pilo.uanic@gmail.com

script:
    - bin/phpspec run -fpretty --verbose
    - bin/behat --no-snippets --verbose -fpretty -p frontend
    - bin/behat --no-snippets --verbose -fpretty -p backend
